#!/bin/bash
parent_path=$(cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P)
cd "$parent_path"
FILES=../data/SGP/*
model=../models/SGP/$1
for f in $FILES
do
datanameext=$(basename "$f")
dataname="${datanameext%.*}"
minizinc --solver Gecode -O0 --random-seed 0 --time-limit 60000 --output-time --output-to-file sgp_gecode_O0_$dataname.txt $model $f
minizinc --solver Gecode -O1 --random-seed 0 --time-limit 60000 --output-time --output-to-file sgp_gecode_O1_$dataname.txt $model $f
minizinc --solver Gecode -O2 --random-seed 0 --time-limit 60000 --output-time --output-to-file sgp_gecode_O2_$dataname.txt $model $f
done

